import {
  ConsoleProfileInfo,
  ConsoleType,
  CustomFilterSettings,
  FilterPresetKey,
  NetworkAppPreset,
  NetworkStreamConfig,
  PerformanceSettings,
  ResolutionConfig,
  ResolutionPresetKey,
} from '../types';

export const CONSOLE_PROFILES: Record<ConsoleType, ConsoleProfileInfo> = {
  auto: {
    id: 'auto',
    name: 'Auto All-Device Detector',
    shortName: 'AUTO DETECT',
    category: 'auto',
    badgeColor: '#00ffcc',
    icon: 'Radio',
    description: 'Auto-scans connected HDMI capture cards, Type-C OTG grabbers, and active Remote Play / Mobile mirror sessions.',
    defaultPreset: 'auto_highest',
    supportedPresets: ['auto_highest', '4k60', '1440p144', '1440p120', '1080p144', '1080p120', '1080p60', '720p144'],
    recommendedFilter: 'device_quality',
    remotePlayInstructions: 'Automatically detects window/app for PS Remote Play, Xbox App, iOS AirPlay, or Scrcpy stream.',
    hardwareGuide: 'Plug in any USB-C OTG or HDMI capture card (Elgato, Cam Link, ShadowCast, MS2109/30, AverMedia).',
    audioFeatures: ['Auto Sync', 'Direct Loopback', 'Low Latency Buffer'],
  },
  ps5: {
    id: 'ps5',
    name: 'PlayStation 5 (PS5 / PS5 Pro)',
    shortName: 'PS5',
    category: 'playstation',
    badgeColor: '#0070d1',
    icon: 'Gamepad2',
    description: 'Ultra HD 4K 60FPS / 1080p 120FPS HDR & Low-Latency Remote Play capture.',
    defaultPreset: '4k60',
    supportedPresets: ['4k60', '1440p120', '1080p120', '1080p60', '720p144'],
    recommendedFilter: 'hdr_boost',
    remotePlayInstructions: 'Connect via official "PS Remote Play" app or Chiaki/Sunshine with 1080p HDR 60fps.',
    hardwareGuide: 'Connect PS5 HDMI OUT -> 4K60/120Hz Capture Card -> USB 3.0 / Type-C port on PC.',
    audioFeatures: ['Tempest 3D Audio Passthrough', '5.1 Channel Mapping', 'Zero Delay'],
  },
  ps4: {
    id: 'ps4',
    name: 'PlayStation 4 / PS4 Pro',
    shortName: 'PS4',
    category: 'playstation',
    badgeColor: '#003791',
    icon: 'Gamepad2',
    description: '1080p 60FPS / 4K30 Pro capture profile with YUY2 zero-latency colorimetry.',
    defaultPreset: '1080p60',
    supportedPresets: ['1080p60', '720p60', '4k60'],
    recommendedFilter: 'bright',
    remotePlayInstructions: 'Set PS Remote Play resolution to 1080p High Frame Rate in PS Remote Play Settings.',
    hardwareGuide: 'Disable HDCP in PS4 Settings -> System -> [Enable HDCP = OFF] before HDMI capture.',
    audioFeatures: ['Stereo PCM 48kHz', 'Direct Monitor'],
  },
  xbox_series: {
    id: 'xbox_series',
    name: 'Xbox Series X | S',
    shortName: 'XBOX SER.X/S',
    category: 'xbox',
    badgeColor: '#107c10',
    icon: 'Tv',
    description: '4K 60FPS / 120FPS VRR Low Latency feed with Xbox Cloud / Remote Play support.',
    defaultPreset: '4k60',
    supportedPresets: ['4k60', '1440p120', '1080p120', '1080p60', '720p144'],
    recommendedFilter: 'esports_clarity',
    remotePlayInstructions: 'Open Xbox Windows App -> Consoles -> Remote Play with direct controller sync.',
    hardwareGuide: 'Connect Xbox HDMI OUT to HDMI 2.0/2.1 capture card. Set Color Depth to 24-bit RGB.',
    audioFeatures: ['Dolby Atmos / Spatial Passthrough', 'PCM Uncompressed'],
  },
  xbox_one: {
    id: 'xbox_one',
    name: 'Xbox One S / Xbox One X',
    shortName: 'XBOX ONE S/X',
    category: 'xbox',
    badgeColor: '#107c10',
    icon: 'Tv',
    description: 'Native 4K30 / 1080p60 capture optimized for Xbox One family with low input lag.',
    defaultPreset: '1080p60',
    supportedPresets: ['1080p60', '720p60', '4k60'],
    recommendedFilter: 'device_quality',
    remotePlayInstructions: 'Stream via Xbox Console Companion or modern Xbox App with instant streaming.',
    hardwareGuide: 'Ensure HDMI cord is rated High-Speed and Xbox output resolution is set to 1080p or 4K.',
    audioFeatures: ['Stereo 16-bit 48kHz', 'Low-pass Limiter'],
  },
  switch: {
    id: 'switch',
    name: 'Nintendo Switch',
    shortName: 'SWITCH',
    category: 'nintendo',
    badgeColor: '#e60012',
    icon: 'Smartphone',
    description: '1080p 60FPS Docked / 720p 60FPS profile with saturated Nintendo color grading.',
    defaultPreset: '1080p60',
    supportedPresets: ['1080p60', '720p60', '720p144'],
    recommendedFilter: 'vibrant_console',
    remotePlayInstructions: 'Use HDMI capture card connected to Switch dock or Genki ShadowCast adapter.',
    hardwareGuide: 'Dock the Nintendo Switch and connect HDMI output to capture card or Type-C OTG.',
    audioFeatures: ['Stereo Linear PCM', 'Dynamic Range Compression Toggle'],
  },
  switch_2: {
    id: 'switch_2',
    name: 'Nintendo Switch 2',
    shortName: 'SWITCH 2',
    category: 'nintendo',
    badgeColor: '#ff3366',
    icon: 'Sparkles',
    description: 'Next-Gen 4K DLSS Docked 60FPS / 1080p 120FPS with HDR color range support.',
    defaultPreset: '4k60',
    supportedPresets: ['4k60', '1440p120', '1080p120', '1080p60'],
    recommendedFilter: 'hdr_boost',
    remotePlayInstructions: 'Next-gen remote play stream capture with low-latency WebRTC / Direct hardware pipeline.',
    hardwareGuide: 'Connect Switch 2 high-speed USB-C / HDMI 2.1 dock to capture device for 4K60/120Hz.',
    audioFeatures: ['Next-Gen Spatial 3D Audio', '48kHz 24-bit Master'],
  },
  ios_mirror: {
    id: 'ios_mirror',
    name: 'iOS Screen Mirror (iPhone / iPad)',
    shortName: 'iOS MIRROR 144Hz',
    category: 'mobile',
    badgeColor: '#00aaff',
    icon: 'Smartphone',
    description: 'Ultra-smooth up to 144 FPS / 120 FPS ProMotion screen mirroring with lossless audio capture.',
    defaultPreset: '1080p144',
    supportedPresets: ['1080p144', '1080p120', '1440p144', '1440p120', '4k60', '720p144'],
    recommendedFilter: 'device_quality',
    remotePlayInstructions: 'Share Screen via AirPlay Mirroring window or QuickTime / UXPlay USB Screen Capture with full audio.',
    hardwareGuide: 'Connect iPhone/iPad using USB-C to HDMI adapter / DP Alt Mode cable directly into your capture device.',
    audioFeatures: ['Lossless AAC / Linear PCM Audio Capture', 'Zero-Jitter Sync', 'Stereo Boost'],
  },
  android_mirror: {
    id: 'android_mirror',
    name: 'Android Screen Mirror (144 FPS / Scrcpy / OTG)',
    shortName: 'ANDROID 144Hz',
    category: 'mobile',
    badgeColor: '#3ddc84',
    icon: 'Smartphone',
    description: 'High-refresh rate 144 FPS gaming screen mirror with low-latency audio loopback & perfect ratio.',
    defaultPreset: '1080p144',
    supportedPresets: ['1080p144', '1080p120', '1440p144', '1440p120', '4k60', '720p144'],
    recommendedFilter: 'esports_clarity',
    remotePlayInstructions: 'Mirror via Scrcpy (--max-fps=144 --audio-codec=raw) or Wireless Display with system audio pass-through.',
    hardwareGuide: 'Connect Android Phone via USB-C DisplayPort Cable / OTG video grabber (supports 120Hz/144Hz DP Alt Mode).',
    audioFeatures: ['High-Bitrate Forwarded Audio', 'Low Latency Buffer Bypass', 'Mic Mix In'],
  },
  type_c_otg: {
    id: 'type_c_otg',
    name: 'Type-C OTG Video Capture',
    shortName: 'TYPE-C OTG',
    category: 'hardware',
    badgeColor: '#ff9900',
    icon: 'Usb',
    description: 'Plug-and-play USB-C OTG grabbers (Cam Link, ShadowCast, MS2130, UVC OTG).',
    defaultPreset: '1080p120',
    supportedPresets: ['4k60', '1080p144', '1080p120', '1080p60', '720p144', '720p60', 'auto_highest'],
    recommendedFilter: 'device_quality',
    remotePlayInstructions: 'OTG hardware receives console feed and sends uncompressed raw frames to browser.',
    hardwareGuide: 'Plug Type-C OTG adapter directly into device USB-C port. No drivers required (UVC standard).',
    audioFeatures: ['UAC Audio Passthrough', 'Analog Mic Line-In'],
  },
  hdmi_grabber: {
    id: 'hdmi_grabber',
    name: 'HDMI / PCIe Capture Device',
    shortName: 'HDMI PRO',
    category: 'hardware',
    badgeColor: '#9933ff',
    icon: 'HardDrive',
    description: 'Dedicated PCIe & USB 3.0 HDMI cards (Elgato HD60X/4K X, AVerMedia, Magewell).',
    defaultPreset: '4k60',
    supportedPresets: ['4k60', '1440p144', '1440p120', '1080p144', '1080p120', '1080p60', '720p144', 'auto_highest'],
    recommendedFilter: 'original',
    remotePlayInstructions: 'Direct hardware loopback from HDMI capture card with sub-frame 5ms latency.',
    hardwareGuide: 'Connect HDMI cable from console to IN port, and USB 3.0 Type-C to computer.',
    audioFeatures: ['Digital HDMI Audio 48kHz', 'Zero Latency Passthrough'],
  },
};

export const RESOLUTION_PRESETS: Record<ResolutionPresetKey, ResolutionConfig> = {
  auto_highest: {
    id: 'auto_highest',
    label: 'Auto Max (Negotiate Best)',
    width: 3840,
    height: 2160,
    frameRate: 144,
    category: 'Automatic',
    aspectRatio: '16:9',
  },
  '4k60': {
    id: '4k60',
    label: '4K UHD @ 60 FPS (3840x2160)',
    width: 3840,
    height: 2160,
    frameRate: 60,
    category: 'Ultra HD',
    recommendedFor: ['ps5', 'xbox_series', 'switch_2', 'hdmi_grabber'],
    aspectRatio: '16:9',
  },
  '1440p144': {
    id: '1440p144',
    label: '2K QHD @ 144 FPS (2560x1440)',
    width: 2560,
    height: 1440,
    frameRate: 144,
    category: 'Ultra High Refresh',
    recommendedFor: ['ios_mirror', 'android_mirror', 'hdmi_grabber'],
    aspectRatio: '16:9',
  },
  '1440p120': {
    id: '1440p120',
    label: '2K QHD @ 120 FPS (2560x1440)',
    width: 2560,
    height: 1440,
    frameRate: 120,
    category: 'High Refresh',
    recommendedFor: ['ps5', 'xbox_series', 'ios_mirror', 'android_mirror'],
    aspectRatio: '16:9',
  },
  '1440p60': {
    id: '1440p60',
    label: '2K QHD @ 60 FPS (2560x1440)',
    width: 2560,
    height: 1440,
    frameRate: 60,
    category: 'High Def',
    aspectRatio: '16:9',
  },
  '1080p144': {
    id: '1080p144',
    label: '1080p FHD @ 144 FPS (1920x1080)',
    width: 1920,
    height: 1080,
    frameRate: 144,
    category: 'Max E-Sports 144Hz',
    recommendedFor: ['ios_mirror', 'android_mirror', 'type_c_otg'],
    aspectRatio: '16:9',
  },
  '1080p120': {
    id: '1080p120',
    label: '1080p FHD @ 120 FPS (1920x1080)',
    width: 1920,
    height: 1080,
    frameRate: 120,
    category: 'High Refresh',
    recommendedFor: ['ps5', 'xbox_series', 'type_c_otg', 'switch_2', 'ios_mirror', 'android_mirror'],
    aspectRatio: '16:9',
  },
  '1080p60': {
    id: '1080p60',
    label: '1080p FHD @ 60 FPS (1920x1080)',
    width: 1920,
    height: 1080,
    frameRate: 60,
    category: 'Standard HD',
    recommendedFor: ['ps4', 'xbox_one', 'switch'],
    aspectRatio: '16:9',
  },
  '720p144': {
    id: '720p144',
    label: '720p HD @ 144 FPS (1280x720)',
    width: 1280,
    height: 720,
    frameRate: 144,
    category: 'Ultra High FPS',
    recommendedFor: ['type_c_otg', 'ios_mirror', 'android_mirror'],
    aspectRatio: '16:9',
  },
  '720p60': {
    id: '720p60',
    label: '720p HD @ 60 FPS (1280x720)',
    width: 1280,
    height: 720,
    frameRate: 60,
    category: 'Low Bandwidth',
    recommendedFor: ['switch', 'ps4'],
    aspectRatio: '16:9',
  },
};

export const FILTER_PRESETS: Record<
  FilterPresetKey,
  { label: string; description: string; css: string }
> = {
  original: {
    label: 'Original Quality',
    description: 'Raw pixel-perfect pass-through with no color distortion',
    css: 'brightness(1) contrast(1) saturate(1)',
  },
  bright: {
    label: 'Bright Filter',
    description: 'Boosts luminance and reveals hidden details in dark scenes',
    css: 'brightness(1.35) contrast(1.05) saturate(1.05)',
  },
  device_quality: {
    label: 'Device Quality',
    description: 'Calibrated dynamic contrast, crisp saturation and hardware balance',
    css: 'contrast(1.18) brightness(1.08) saturate(1.22)',
  },
  shadowed: {
    label: 'Shadowed Filter',
    description: 'Cinematic deep blacks and richer shadows for immersive gaming',
    css: 'brightness(0.82) contrast(1.28) saturate(1.15)',
  },
  more_lighting: {
    label: 'More Lighting',
    description: 'HDR-style gamma lift and high-key exposure compensation',
    css: 'brightness(1.22) contrast(1.12) saturate(1.1)',
  },
  vibrant_console: {
    label: 'Vibrant Console',
    description: 'Rich, vivid color pop tuned for Nintendo Switch & vibrant titles',
    css: 'saturate(1.45) contrast(1.15) brightness(1.04)',
  },
  esports_clarity: {
    label: 'E-Sports Clarity',
    description: 'High contrast and tuned brightness for competitive visibility',
    css: 'contrast(1.3) brightness(1.15) saturate(0.95)',
  },
  hdr_boost: {
    label: 'HDR Boost',
    description: 'Simulated high-dynamic-range curve with enhanced peak highlights',
    css: 'contrast(1.24) brightness(1.1) saturate(1.3) hue-rotate(2deg)',
  },
  custom: {
    label: 'Custom Colorimetry',
    description: 'User-defined fine-grain manual image controls',
    css: '',
  },
};

export const DEFAULT_CUSTOM_FILTERS: CustomFilterSettings = {
  brightness: 100,
  contrast: 100,
  saturate: 100,
  hueRotate: 0,
  sharpness: 0,
  gamma: 1.0,
};

export const DEFAULT_PERFORMANCE_SETTINGS: PerformanceSettings = {
  showFpsOverlay: false, // Default OFF as requested
  showLatencyDiagnostic: false, // Default OFF until activated
  rtxLowLatency: true, // Highest low-latency mode enabled
  frameGeneration: false, // Optical flow / frame interpolation toggle
  autoSmoothViewing: true, // Smooth cadence pacing
  perfectRatioLock: true, // Prevents warping/distortion
};

export function buildFilterCss(
  presetKey: FilterPresetKey,
  custom: CustomFilterSettings
): string {
  if (presetKey !== 'custom') {
    return FILTER_PRESETS[presetKey].css;
  }
  const b = custom.brightness / 100;
  const c = custom.contrast / 100;
  const s = custom.saturate / 100;
  const h = custom.hueRotate;
  return `brightness(${b}) contrast(${c}) saturate(${s}) hue-rotate(${h}deg)`;
}

export const DEFAULT_NETWORK_STREAM_CONFIG: NetworkStreamConfig = {
  ip: '192.168.1.100',
  port: '8080',
  protocol: 'http',
  path: '/',
  streamType: 'auto',
  targetFps: 60,
  autoReconnect: true,
  lowLatencyBuffer: true,
  audioEnabled: false,
  audioPort: '8080',
  audioPath: '/audio.wav',
  presetApp: 'screen_stream',
};

export const NETWORK_APP_PRESETS: NetworkAppPreset[] = [
  {
    id: 'screen_stream',
    name: 'Screen Stream over HTTP',
    defaultPort: '8080',
    defaultPath: '/',
    streamType: 'mjpeg',
    audioSupported: false,
    description: 'Popular free app on Android & iOS. High-refresh MJPEG stream over local Wi-Fi.',
    badge: 'Android / iOS',
  },
  {
    id: 'ip_webcam',
    name: 'IP Webcam (Android)',
    defaultPort: '8080',
    defaultPath: '/video',
    streamType: 'mjpeg',
    audioSupported: true,
    defaultAudioPath: '/audio.wav',
    description: 'Android IP Webcam stream. Supports video + uncompressed PCM audio loopback.',
    badge: 'Android',
  },
  {
    id: 'droidcam',
    name: 'DroidCam Screen / Cam',
    defaultPort: '4747',
    defaultPath: '/video',
    streamType: 'mjpeg',
    audioSupported: false,
    description: 'Ultra-low latency DroidCam port over Wi-Fi or USB tethering.',
    badge: 'Android / iOS',
  },
  {
    id: 'vlc_obs',
    name: 'OBS / VLC HTTP Stream',
    defaultPort: '8080',
    defaultPath: '/live',
    streamType: 'video',
    audioSupported: true,
    description: 'Direct H.264 / MP4 / WebM HTTP live stream from OBS Studio or VLC.',
    badge: 'Desktop / Relay',
  },
  {
    id: 'custom',
    name: 'Custom IP & Port',
    defaultPort: '8080',
    defaultPath: '/video',
    streamType: 'auto',
    audioSupported: true,
    defaultAudioPath: '/audio',
    description: 'Input any custom IPv4 / domain, port, and endpoint path.',
    badge: 'Advanced',
  },
  {
    id: 'demo',
    name: 'Local Test Pattern (Demo)',
    defaultPort: '3000',
    defaultPath: '/demo',
    streamType: 'demo',
    audioSupported: true,
    description: 'Instant 60/120/144 FPS animated test pattern to verify player and filters immediately.',
    badge: 'Zero-Hardware Test',
  },
];

// Known capture card identifiers and keywords
export const CAPTURE_CARD_KEYWORDS = [
  'capture',
  'cam link',
  'elgato',
  'magewell',
  'avermedia',
  'shadowcast',
  'ms2109',
  'ms2130',
  'uvc',
  'hdmi',
  'otg',
  'usb video',
  'video capture',
  'grabber',
  'ultrastudio',
  'decklink',
  'xr1',
  'genki',
  'razer ripsaw',
  'evga',
  'mirabox',
  'pengo',
  'acasis',
  'scrcpy',
  'airplay',
  'screen mirror',
];
